version: '2'

services:
  box:
    build:
      context: .
      dockerfile: ./compose/box/Dockerfile
    depends_on:
      - redis
      - nginx
    volumes:
      - /tmp:/tmp

  redis:
    build: ./compose/redis

  nginx:
    build: ./compose/box/nginx
    volumes:
      - /tmp:/tmp
    ports:
      - "0.0.0.0:8000:8000"


