version: '2'

services:
  box:
    build:
      context: .
      dockerfile: ./compose/box/Dockerfile
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp
      - /var/log/nginx:/var/log/nginx
    command: ["python", "/app/run_box.py"]

  redis:
    image: redis:4.0.1-alpine

  nginx:
    build: ./compose/box/nginx
    volumes:
      - /tmp:/tmp
      - /var/log/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    depends_on:
      - box


