# Redis
REDIS_HOST: "redis" # If docker is used, then url should be redis://redis:6379
REDIS_PORT: 6379
DB: 0

# Should be a list (Start with an indent, a dash and a space)
ENTRANCE_URLS:
  - "https://140.115.153.213:8080/dandelion/ws"

# BOX Settings
BOX_SERVER_IP: "127.0.0.1"
BOX_CLIENT_IP:
BOX_PORT: 8080
BASE_DIRECTORY: "/tmp" # Directory to place received files
BOX_PING_ENTRANCE_FREQ: 5
SERVER_REDIS_MINSIZE: 5
SERVER_REDIS_MAXSIZE: 10
CLIENT_REDIS_MINSIZE: 1
CLIENT_REDIS_MAXSIZE: 5

#PUBLISHER Settings
PUBLISHER_IP: "192.168.1.44"
PUBLISHER_PORT: 8081
MIN_HTTP_PEERS: 20
PUBLISHER_REDIS_MINSIZE: 5
PUBLISHER_REDIS_MAXSIZE: 10
PUBLISHER_PING_ENTRANCE_FREQ: 10


#ENTRANCE Settings
ENTRANCE_IP: "140.115.153.213"
ENTRANCE_PORT: 8080
ENTRANCE_REDIS_MINSIZE: 5
ENTRANCE_REDIS_MAXSIZE: 10
ENTRANCE_EXPIRE_BOX_TIME: 120
AMOUNT_OF_BOXES_PER_REQUEST: 20


### Settings should not be touched
BASE_URL: "/dandelion"
WEBSOCKET_URL: "ws"

