version: '2'

services:
  entrance:
    build:
      context: .
      dockerfile: ./compose/entrance/Dockerfile
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0-alpine

  nginx:
      build:
        context: .
        dockerfile: ./compose/entrance/nginx/Dockerfile
      ports:
        - "7070:7070"
      depends_on:
        - entrance

