version: '2'

services:
  entrance:
    build:
      context: .
      dockerfile: ./compose/entrance/Dockerfile
    depends_on:
      - redis-entrance
    volumes:
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime
    command: ["python", "/app/run_entrance.py"]

  redis-entrance:
    image: redis:4.0-alpine

  nginx:
      build:
        context: .
        dockerfile: ./compose/entrance/nginx/Dockerfile
      ports:
        - "7070:7070"
      depends_on:
        - entrance

