version: '2'

services:
  publisher:
    build:
      context: .
      dockerfile: ./compose/publisher/Dockerfile
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp

  redis:
    image: redis:4.0-alpine
