version: '2'

services:
  publisher:
    build:
      context: .
      dockerfile: ./compose/publisher/Dockerfile
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime
    command: ["python", "/app/run_publisher.py"]

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"  #Let website to connect docker's redis
